### ISSUE TITLE
V6 and PHP 8.2 compatibility

### ISSUE THREAD

**Issue by kmzeitgleich** [cundd/rest#76] opened 2023-07-26 11:42 UTC
I am Using PHP 8.2.4 with TYPO3 12.4.4 and I have a List of Fatal Errors because of PHP return types

1. ServerRequestProxyTrait.php is an implementation of ServerRequestInterface, but that interface got a lot of return types in the functions

Example: Fatal error: Declaration of Cundd\Rest\Request::getProtocolVersion() must be compatible with Psr\Http\Message\MessageInterface::getProtocolVersion(): string

Solution: You add the return types to the functions

2. Documentation/Handler/DummyRequest.php has a similar Problem I think, adding the correct return types will probably fix it

I have set 'exceptionalErrors' => 12290, in the settings.php (previously known as LocalConfiguration.php)

**Comment by cundd** [comment] 2023-07-26 12:00
Hi

Thank you for the bug report. I think the problem is, that Composer may choose `psr/http-message` version 2, which has return types set. I'll see if I can provide support for v1 and v2.

**Comment by cundd** [comment] 2023-07-27 08:29
@kmzeitgleich can you give the latest v6 version a try?

**Comment by kmzeitgleich** [comment] 2023-07-27 08:37
It does not give an error now, but I have not tried using it yet.
But I guess it is solved

**Comment by cundd** [comment] 2023-07-27 08:40
Alright. I'll close the issue.

Please open a new one if you find something else :)

**Closed as completed by cundd** 2023-07-27 08:40 UTC
