### ISSUE TITLE
Exception when applying the default configuration.

### ISSUE THREAD

**Issue by 4allportaleabdullah** [cundd/rest#78] opened 2024-04-02 09:35 UTC
Hi, I am encountering the following exception when trying to test with version 12+.
I have used v4 and v5 before with no problems.

I know that v6 has not been released yet, but can you tell if this is a misconfiguration or a bug?

Thank you in advance.

Branch: v6
Typo3-Version: 12.4.11
Default configuration as described in : https://rest.corn.rest/Configuration/ 

Core: Exception handler (WEB): Uncaught TYPO3 Exception: TYPO3\CMS\Frontend\Controller\TypoScriptFrontendController::__construct(): Argument #2 ($site) must be of type TYPO3\CMS\Core\Site\Entity\Site, TYPO3\CMS\Core\Site\Entity\NullSite given, called in /var/www/html/typo3_src-12.4.11/typo3/sysext/core/Classes/Utility/GeneralUtility.php on line 2985 | TypeError thrown in file /var/www/html/typo3_src-12.4.11/typo3/sysext/frontend/Classes/Controller/TypoScriptFrontendController.php in line 524. Requested URL: http://host.docker.internal:8080/rest/virtual_object-gallery/	Delete similar errors

**Comment by cundd** [comment] 2024-04-02 09:41
I think the problem is, that TYPO3 couldn't find a site for the given domain. Can you check if there is a correct site configuration?

**Comment by Lars114** [comment] 2024-04-05 14:58
Hi, 

I have a Site Management configuration.
<img width="1161" alt="SiteManagement" src="https://github.com/cundd/rest/assets/166145305/496b2ee4-bdb5-4069-9814-fde73a0b2af7">

and call to url `http://localhost:8080/` opens a page with `HELLO WORLD!`.

You have further ideas? 

Thank you in advance.

**Comment by cundd** [comment] 2024-04-05 18:52
What happens if you open [http://host.docker.internal:8080](http://host.docker.internal:8080)?

**Comment by Lars114** [comment] 2024-04-12 09:37
Thank you for your answer. The problem was in the resolution of the url in the docker container.
I have now configured the fixed url ' http://typo3.4allportal.com/`.
The above error is fixed. 

Instead, I get an error from multipart `POST 
http://typo3.4allportal.com/rest/virtual_object-gallery/` with `Authorisation` header set.
The error response is `403 Forbidden` from 
```php
return $this->responseFactory->createErrorResponse('Forbidden', 403, $request);
```

Possible I have to set 
```
RewriteRule .* - [E=HTTP_AUTHORIZATION:%{HTTP:Authorization},L]
```
to allow basic authentication? When yes in which file and where. I tried in `/var/www/html/.htaccess` but not worked. 


Authentication with 
```
POST http://typo3.4allportal.com/rest/auth/login HTTP/1.1
Host: typo3.4allportal.com
Cache-Control: no-cache
Content-Type: application/x-www-form-urlencoded

username=administrator&apikey=Crossmedia1!
```
responses with 
```json
{
  "status": "logged-in"
}
```
but I need basic authentication.

No error logged in typo3 `http://typo3.4allportal.com/typo3/module/system/BelogLog`

Thank you in advance.

**Comment by cundd** [comment] 2024-04-12 19:55
You have to check if the sent data is present in one of the checked headers (see: https://github.com/cundd/rest/blob/v6/Classes/Authentication/BasicAuthenticationProvider.php#L35).

I can't tell how this has to be configured in your specific environment.

**Comment by cundd** [comment] 2024-04-12 19:56
I'm closing this issue since the original question seems to be answered

**Closed as completed by cundd** 2024-04-12 19:56 UTC
